# Generated by Django 2.2 on 2021-10-30 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211030_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 30, 16, 26, 18, 286965, tzinfo=utc)),
        ),
    ]
